# Pandas

In [ ]:
import pandas as pd
import sklearn.decomposition

pd.DataFrame #creates a Dataframe object of the selected input. Creates a 2D table, with rows as dimension 0, columns dimension 1, and each column is selectable as a string.
# df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],       #the data/observations
# ...      index=['cobra', 'viper', 'sidewinder'],  #the row lables==index
# ...      columns=['max_speed', 'shield'])         #the column labels=attributes
pd.isnull() #returns a truth table of where values are missing in the table.
pd.read_csv() #reads csv data from a csv file format.
pd.get_dummies(data: Any, dummy_na: bool= False, columns:Any = None) #Does the onehot encoding itself. Convert categorical variables of X_train into dummy/indicator variables.

pd.DataFrame.dropna() #Return DataFrame with labels on given axis omitted where (all or any) data are missing.
pd.DataFrame.drop_duplicates() #Return Dataframe with duplicate rows removed.
pd.DataFrame.drop(labels: Any = None, axis: str | int = 0, index: Any = None, columns: Any = None,inplace: bool = False,) #drops certain columns of the panda data from, returns a pandas object without the columns. columns= also works.
pd.DataFrame.info() #returns attributes, how many null values each table has, and datatype in each cell.
pd.DataFrame.describe() #displays table.
pd.DataFrame.loc() #access groups of rows or columns by label. You enter "label" or ["labels","labels"], and it will search rows and columns.
#df.loc[(df['class'] != 2)] #return dataframe where the values of the class attribute are not 2.
pd.DataFrame.replace(to_replace="values in the df to replace",value="what to replace the df values with")# You can search a column and replace values by column, but this method replaces everything in the dataframe.
#df = df.replace({"class": {0: -1}}) #in class, replace 0 with -1.
pd.DataFrame.plot.scatter(x='feature1', y='feature2') #builtin method of creating a scatter plot form data.
pd.DataFrame.corr() #returns a correlation table of each of the features.
pd.DataFrame.head(n=)#returns the top n rows.
pd.DataFrame.hist(figsize=(16,16), grid=False) #returns the histogram of each feature.
pd.DataFrame.boxplot(["columns"]) #returns the boxplot of features
pd.Dataframe["column"].value_counts() #returns the counts of categorical, or numerical data in a column
pd.DataFrame.reset_index(inplace=True) #resents the index of a dataframe,
pd.DataFrame.set_index(keys=,inplace=True) #Set the DataFrame index (row labels) using one or more existing columns or arrays (of the correct length). Keys can be either a single column key, a single array of the same length as the calling DataFrame, or a list containing an arbitrary combination of column keys and arrays.
pd.DataFrame.copy(deep=True) #Creates an actual copy, not just an assignment.
pd.DataFrame.nunique(self,axis: str | int = 0, dropna: bool = True)) #Count distinct elems in axis. Return Series with number of distinct elements. Can ignr NaN, when dropna is True.
pd.DataFrame.keys() #returns the keys, or column names, of the object. == to .columns.

# Seaborn

In [ ]:
import seaborn as sns
sns.set_style() #sets the style of the plot about to write. Color style "whitegrid"
sns.scatterplot(x=,y=,hue=,data=)# X and Y specify coordinates of specific variables. hue differentiates points based on categorical or numerical data. data is the object, such as a pd.dataframe or numpy array, that x and y come from.
sns.heatmap(data=,annot=) #heatmap of values,ranging from max to min of the data. Sould normalize data beforehand.
sns.pairplot(data=,vars=) #plots pairwise relationship of data. Plots each feature as x and y, diagonal shows a histogram of each feature.

# Keras

In [3]:
import keras
keras.models.Sequential() #creates an instance of the keras neural net. Need to add layers.
keras.layers.Dense() #layer format.
keras.models.Sequential.add()
keras.models.Sequential.compile(optimizer='rmsprop',loss=None,metrics=None,weighted_metrics=None,steps_per_execution=None,jit_compile=None,)
keras.models.Sequential.predict_on_batch()

TypeError: __init__() missing 1 required positional argument: 'units'

## Keras metrics
AUC: Approximates the AUC (Area under the curve) of the ROC or PR curves.

Accuracy: Calculates how often predictions equal labels.

BinaryAccuracy: Calculates how often predictions match binary labels.

BinaryCrossentropy: Computes the crossentropy metric between the labels and predictions.

BinaryIoU: Computes the Intersection-Over-Union metric for class 0 and/or 1.

CategoricalAccuracy: Calculates how often predictions match one-hot labels.

CategoricalCrossentropy: Computes the crossentropy metric between the labels and predictions.

CategoricalHinge: Computes the categorical hinge metric between y_true and y_pred.

CosineSimilarity: Computes the cosine similarity between the labels and predictions.

FalseNegatives: Calculates the number of false negatives.

FalsePositives: Calculates the number of false positives.

Hinge: Computes the hinge metric between y_true and y_pred.

IoU: Computes the Intersection-Over-Union metric for specific target classes.

KLDivergence: Computes Kullback-Leibler divergence metric between y_true and

LogCoshError: Computes the logarithm of the hyperbolic cosine of the prediction error.

Mean: Computes the (weighted) mean of the given values.

MeanAbsoluteError: Computes the mean absolute error between the labels and predictions.

MeanAbsolutePercentageError: Computes the mean absolute percentage error between y_true and

## Keras loss
class BinaryCrossentropy: Computes the cross-entropy loss between true labels and predicted labels. The CategoricalCrossentropy also computes the cross-entropy loss between the true classes and predicted classes. The labels are given in an one_hot format.

class BinaryFocalCrossentropy: Computes the focal cross-entropy loss between true labels and predictions.

class CategoricalCrossentropy: Computes the crossentropy loss between the labels and predictions.

class CategoricalHinge: Computes the categorical hinge loss between y_true & y_pred.

class CosineSimilarity: Computes the cosine similarity between labels and predictions.

class Hinge: Computes the hinge loss between y_true & y_pred.

class Huber: Computes the Huber loss between y_true & y_pred.

class KLDivergence: Computes Kullback-Leibler divergence loss between y_true & y_pred.

class LogCosh: Computes the logarithm of the hyperbolic cosine of the prediction error.

class Loss: Loss base class.

class MeanAbsoluteError: Computes the mean of absolute difference between labels and predictions.

class MeanAbsolutePercentageError: Computes the mean absolute percentage error between y_true & y_pred.

class MeanSquaredError: Computes the mean of squares of errors between labels and predictions.

class MeanSquaredLogarithmicError: Computes the mean squared logarithmic error between y_true & y_pred.

class Poisson: Computes the Poisson loss between y_true & y_pred.

class Reduction: Types of loss reduction.

class SparseCategoricalCrossentropy: Computes the crossentropy loss between the labels and predictions.
y_true = [0, 1,2]
y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1],[0.1, 0.8, 0.1]]

class SquaredHinge: Computes the squared hinge loss between y_true & y_pred.

# SVM

In [ ]:
import numpy as np
import cvxpy as cp
"class version"
class LinearSVM:
    def __init__(self, soft=False, C=1):
        self.relax = soft
        self.C = C
        self.M = None # number of features/dimensions
        self.N = None # number of training data points

        self.X = None
        self.y = None

        self.w = None #our weight. 13 weights
        self.b = None
        self.e = None

    def fit(self, X, y):
        (self.N, self.M) = X.shape
        self.X = np.asarray(X)
        self.y = np.asarray(y).reshape(-1, 1)

        w = cp.Variable((self.M, 1))
        b = cp.Variable()
        e = cp.Variable((self.N, 1))

        if self.relax: # Soft-margin SVM
            objective = cp.Minimize(cp.sum(cp.square(w)) * 0.5 + cp.sum(e) * self.C)
            constraints = [cp.multiply(self.y, (self.X @ w + b)) >= 1 - e, e >=0] #constraints of how many can be within the margin. So...
        else: # Hard-margin SVM
            objective = cp.Minimize(cp.sum(cp.square(w)) * 0.5) #this is minimum(1/2(w^2)
            constraints = [cp.multiply(self.y, (self.X @ w + b)) >= 1] #this is the constraint. Objective is reached, so long as y*support vector is above 1.

        prob = cp.Problem(objective, constraints)

        prob.solve()
        self.w = w.value
        self.b = b.value
        self.e = e.value
        print(f'Status: {prob.status}')
        print(f"Objective Value: {prob.value}")

    def predict(self, X):
        return np.sign((np.asarray(X) @ self.w + self.b))

    def getSupportVec(self):
        if self.relax: # Soft-margin SVM
            return (self.y * (self.X @ self.w + self.b) - 1 + self.e <= 1e-10)
        else: # Hard-margin SVM
            return (self.y * (self.X @ self.w + self.b) - 1 <= 1e-10)
    def printSupportVec(self):
        "lower vector {}*({} X {} + {})-1+{}".format(self.y,self.X,self.w,self.b,self.e)
    def getParams(self):
        return self.w

In [ ]:
"sklearn version"
from sklearn import preprocessing
from sklearn.svm import SVC, LinearSVC
scaler = preprocessing.StandardScaler() #initiates a scaler class. Replaces all values in a population with a zscore.
scaler.fit_transform() #fits and transforms the inputed data into a zscore.
clf = SVC(kernel='linear',)              #initiaties a support vector machine class for linear regression. Can fit and predict on its own.
clf_li = LinearSVC(dual=False,loss="hinge")          #creates a linear classification object. Can fit and predict on its own.
#Generally,linearSVC() handles scalability better.
clf.support_vectors_() #returns the support vectors, or the points which make the support vectors.
clf.decision_function()

# sklearn

In [2]:
import sklearn
sklearn.decomposition.PCA(n_components=number of data attributes)#initialize PCA class
pca=sklearn.decomposition.PCA.fit()#returns the instance.
loadings = pd.DataFrame(pca.components_.T, columns=['PC%s' % _ for _ in range(len(df_normalized.columns))], index=df.columns)
sklearn.decomposition.PCA.components_ ##gives you the PCA weights.
sklearn.decomposition.PCA.explained_variance_#how much of the variance in the data points is explained by the PCA
sklearn.decomposition.PCA.explained_variance_ratio_#tells how much of the variance in the datapoints is explained by the PCA out of the others.
sklearn.metrics.classification_report(ytrue=,y_pred=) #returns a report of all the accuracy, ect, of the data
sklearn.metrics.confusion_matrix(y_true=,y_pred=) #creates a confusion matrix, to see how many times a category or prediction was wrong, and how many times it was labeled as a certain other thing.
encoder = preprocessing.OrdinalEncoder() # Encodes each category as integers. From 0 to n_classes - 1
y_encoder = preprocessing.LabelEncoder() # Same functionality but designed for the dependent variable.
deg = 5

poly = sklearn.preprocessing.PolynomialFeatures(degree=deg, include_bias=False) #Setup the model
demo = sklearn.preprocessing.PolynomialFeatures.fit_transform(np.arange(5).reshape(-1, 1))#enriching the data, by transforming each feature, by raising each feature to the degree.

#Regularization is one way to prevent overfitting.
# The idea is to penalize the coefficients so that you are discouraged to learn a complex model. <br >
# To achieve so, we would add a regularization term to the loss function.
#first fit the data to transformation.
X_poly = poly.fit_transform(X.reshape(-1, 1))
# Polynomial Regression with l1-regularization
polyRegL1 = sklearn.linear_model.Lasso(alpha=0.2).fit(X_poly, y.reshape(-1, 1))
# Polynomial Regression with l2-regularization
polyRegL2 = sklearn.linear_model.Ridge(alpha=0.2).fit(X_poly, y.reshape(-1, 1))
TREE=sklearn.tree.DecisionTreeClassifier(criterion="gini or information gain", max_depth=3, random_state=0) # max depth is how many levels. Creats a classification tree, and you can insert your own split calculation function.
clf_en = sklearn.tree.DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0) #This uses criterion entropy, which is just the information gain.
sklearn.metrics.accuracy_score() #In multilabel classification, this function computes subset accuracy: the set of labels predicted for a sample must exactly match the corresponding set of labels in y_true.

SyntaxError: invalid syntax (96600107.py, line 2)

# Numpy

In [ ]:
import numpy as np
np.vstack
np.dot

# imblearn

In [ ]:
import imblearn
imblearn.over_sampling.RandomOverSampler(data)#Randomly over samples the data, by taking multiple rows and duplicating them, while leaving the original.

Normal distribution: Also known as the "bell curve", this is a specific statistical distribution where a roughly equal observations fall above and below the mean, the mean and the median are the same, and there are more observations closer to the mean. The normal distribution is also known as the Gaussian distribution.

When copying, or creating dropped dataframes, then you need to use the deep copy method. Shallow copy is when you have an array X, then select parts of an array to be Y. Mess with X, you mess with Y. But if you deep copy the indeces, then you can mess with X, without messing with Y.

In [14]:
import numpy as np
x=np.linspace(5,20,6)
display(x)

array([ 5.,  8., 11., 14., 17., 20.])

In [15]:
y=x[2:4:1]
display(y)
x=np.linspace(20,30,6)
print(y)
display(x)

array([11., 14.])

[11. 14.]


array([20., 22., 24., 26., 28., 30.])

In [ ]:
something=[1 if i>thing else 0 for i in yhat]

# Category Coders